intel-retail/rtsf-at-checkout-reference-design

- rtsf-at-checkout-device-scale/driver/scaleDriver.go
Signed-off-by: Valina Li <valina.li@intel.com>
> fix: verified to return nil when scale is not connected

- rtsf-at-checkout-cv-region-of-interest/src/enterexit.py
Signed-off-by: Marc-Philippe Fuller <marc-philippe.fuller@intel.com>
> refactor: add validation to camFrameStore

- rtsf-at-checkout-cv-region-of-interest/src/enterexit.py
use different default directory for frame store instead of tmp as result of bandit scanning result
Signed-off-by: Jim Wang <yutsung.jim.wang@intel.com>
> fix: fix from bandit scan results

- README.md
- loss-detection-app/res/device-mqtt/devices/device-list.toml
- loss-detection-app/res/device-rest/devices/device-list.toml
- rtsf-at-checkout-device-scale/Dockerfile
- rtsf-at-checkout-device-scale/cmd/res/configuration.toml
- rtsf-at-checkout-device-scale/cmd/res/devices/device-list.toml
- rtsf-at-checkout-event-reconciler/Dockerfile
- rtsf-at-checkout-event-reconciler/res/configuration.toml
- rtsf-at-checkout-loss-detector/Dockerfile
- rtsf-at-checkout-loss-detector/res/configuration.toml
- rtsf-at-checkout-loss-detector/res/docker/configuration.toml
- rtsf-at-checkout-product-lookup/Dockerfile
> fix: license in dockerfiles, toml files, and gstreamer disclaimer

- LICENSE
Signed-off-by: Valina Li <valina.li@intel.com>
> fix: update general license file year

- .github/.reviewdogConfig.yml
- .github/workflows/gotest.yaml
- .github/workflows/integrationTest.yaml
- Makefile
> feat: Integration tests

- .github/workflows/integrationTest.yaml
- Makefile
> fix: Makefile hadolint

- .github/.reviewdogConfig.yml
- .github/workflows/integrationTest.yaml
- Makefile
> fix: hadolint and output

- .github/workflows/trivyimagescan.yaml
> fix: Add all image scans

- .github/workflows/trivyimagescan.yaml
> fix: Update scan name

- README.md
> fix: Update github doc link

- Makefile
> fix: Makefile update

- Makefile
- loss-detection-app/docker-compose.edgex.yml
closes: #68 
- Run `make run-edgex`
- Run `make run-portainer`
- Check that EdgeX Core Services are up and running properly
> feat: migrate edgex compose file to EdgeX v3.0

- loss-detection-app/docker-compose.portainer.yml
- Updates Portainer
close: #**70**
closes: #70 
- Run `make run-portainer` 
- Navigate to `localhost:9000`
- `docker compose -f loss-detection-app/docker-compose.portainer.yml down`
> feat: Update Portainer to use ce image

- rtsf-at-checkout-cv-region-of-interest/src/enterexit.py
Closes #78
changing enter/exit mqtt topic to align with async topic for EdgeX 3.0
close: #78
> refactor: Update MQTT to EdgeX 3.0 for async messages

- docs/configuration/index.html
- docs/device_services/index.html
- docs/phases/phase1/index.html
- docs_src/configuration.md
- docs_src/device_services.md
- docs_src/notifications.md
- docs_src/phases/phase1.md
- loss-detection-app/postman-collections/POS and Scale (No Suspect items).postman_collection.json
- loss-detection-app/postman-collections/POS and Scale (Suspect scale item).postman_collection.json
- loss-detection-app/postman-collections/POS, Scale, CV (No Suspect items).postman_collection.json
- loss-detection-app/postman-collections/POS, Scale, CV (Suspect CV and Scale items).postman_collection.json
- loss-detection-app/postman-collections/POS, Scale, RFID (No Suspect items).postman_collection.json
- loss-detection-app/postman-collections/POS, Scale, RFID (Suspect RFID items).postman_collection.json
Updated document endpoint to reflect v3 endpoint changes.
all /v2/ are now /v3/ to match the v3 format.
> docs: Update documents to reflect the EdgeX v3 endpoint changes

- .github/workflows/scorecard.yml
- README.md
> feat: Add badges

- .github/dependabot.yml
> chore: Update dependabot config to run daily on gomod

- Makefile
- loss-detection-app/docker-compose-ovms.yml
- loss-detection-app/docker-compose.vap.yml
- loss-detection-app/ovms-models/config.json
Integrate ovms
- Download product-detection-0001 models using `make models`
- Copy only bin & xml files into directory `loss-detection-app/ovms-models/product-detection-001/1`
- make `run-ovms`
- no errors in docker containers
- PS: I will be adding another script to directly download models following the ovms structure
> feat: integrate ovms

- Makefile
- loss-detection-app/docker-compose.vap.yml
- rtsf-at-checkout-cv-region-of-interest/Dockerfile
- rtsf-at-checkout-cv-region-of-interest/requirements.txt
- rtsf-at-checkout-cv-region-of-interest/src/enterexit.py
- rtsf-at-checkout-cv-region-of-interest/src/grpc_python.py
- Download product-detection-0001 models using `make models`
- Copy only bin & xml files into directory `loss-detection-app/ovms-models/product-detection-0001/1`
- copy sample video into `loss-detection-app/video-samples` 
- make `run-vap-ovms`
- no errors in docker containers, specifically `openvino` & `cv-region-of-interest`
- use mqtt client tool like MQTTBox & subscribe to edgex-mqtt-broker:1883 on topics - `AnalyticsData` & `incoming/data/cv-roi-mqtt/cv-roi-event`
- `AnalyticsData` shows inference data & `incoming/data/cv-roi-mqtt/cv-roi-event` shows the event posted for product detected
- Pipeline-Server(dlstreamer) code is commented & not removed
> feat: integrate ovms with end-to-end rtsf use case flow

- rtsf-at-checkout-cv-region-of-interest/requirements.txt
> fix: Dependabot updates

- .github/workflows/build.yaml
- .github/workflows/codeql.yaml
- .github/workflows/gotest.yaml
- .github/workflows/integrationTest.yaml
- .github/workflows/reports.yaml
- .github/workflows/reviewdog.yaml
- .github/workflows/scorecard.yml
- .github/workflows/trivy-scan.yaml
- .github/workflows/trivyimagescan.yaml
- Updates the GitHub Actions jobs to improve scanning and automated image builds
> feat: Update GitHub actions jobs
